// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2WAvQrEDFb0xzXc1xApWbvNHcgFwBE9s',
    appId: '1:780277909387:web:c6c6230916f5688293d18e',
    messagingSenderId: '780277909387',
    projectId: 'doc2heal-8428c',
    authDomain: 'doc2heal-8428c.firebaseapp.com',
    storageBucket: 'doc2heal-8428c.appspot.com',
    measurementId: 'G-XMYG4LF7CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6qLMOOOhkVobmanfQgalMpjWOsv519FE',
    appId: '1:780277909387:android:a13a6f59b337492d93d18e',
    messagingSenderId: '780277909387',
    projectId: 'doc2heal-8428c',
    storageBucket: 'doc2heal-8428c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP9_8NVULKUiD18Vhl355WB4tBTpOoScE',
    appId: '1:780277909387:ios:522fecddfb332e9593d18e',
    messagingSenderId: '780277909387',
    projectId: 'doc2heal-8428c',
    storageBucket: 'doc2heal-8428c.appspot.com',
    iosBundleId: 'com.example.doc2heal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP9_8NVULKUiD18Vhl355WB4tBTpOoScE',
    appId: '1:780277909387:ios:24197c2ea5bcc06393d18e',
    messagingSenderId: '780277909387',
    projectId: 'doc2heal-8428c',
    storageBucket: 'doc2heal-8428c.appspot.com',
    iosBundleId: 'com.example.doc2heal.RunnerTests',
  );
}
